CREATE TABLE
JOB_INSTANCE_STATUS (
JOB_INSTANCE_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
PROCESS_INSTANCE_ID BIGINT(20),
PROCESS_INSTANCE_NAME VARCHAR(255),
JOB_NAME VARCHAR(255) NOT NULL,
JOB_PROJECT VARCHAR(128),
JOB_DISPLAY_NAME VARCHAR(255),
JOB_GUID VARCHAR(100) NOT NULL,
JOB_EXT_ID VARCHAR(255),
JOB_INFO VARCHAR(255),
ROOT_JOB_GUID VARCHAR(100),
WORK_ITEM VARCHAR(1024),
TIME_RANGE_START TIMESTAMP(3) NULL default NULL,
TIME_RANGE_END TIMESTAMP(3) NULL default NULL,
VALUE_RANGE_START VARCHAR(512),
VALUE_RANGE_END VARCHAR(512),
JOB_STARTED_AT TIMESTAMP(3)NULL default NULL,
JOB_ENDED_AT TIMESTAMP(3)NULL default NULL,
JOB_RESULT VARCHAR(1024),
COUNT_INPUT INT,
COUNT_OUTPUT INT,
COUNT_UPDATED INT,
COUNT_REJECTED INT,
COUNT_DELETED INT,
RETURN_CODE INT,
RETURN_MESSAGE TEXT,
HOST_NAME VARCHAR(255),
HOST_PID INT,
HOST_USER VARCHAR(128) ,
PRIMARY KEY
(JOB_INSTANCE_ID)
) DEFAULT CHARSET=UTF8;

CREATE INDEX JOB_INSTANCE_STATUS_JOB_GUID ON JOB_INSTANCE_STATUS(JOB_GUID);
CREATE INDEX JOB_INSTANCE_STATUS_JOB_NAME ON JOB_INSTANCE_STATUS(JOB_NAME);
CREATE TABLE JOB_INSTANCE_CONTEXT (
JOB_INSTANCE_ID BIGINT NOT NULL,      
--reference to the job instance
ATTRIBUTE_KEY VARCHAR(100) NOT NULL,  
--context variable name
ATTRIBUTE_VALUE VARCHAR(1024),        
--textual representation of the value
ATTRIBUTE_TYPE 
VARCHAR
(32) 
NOT NULL
,  
--Java class name of the value
IS_OUTPUT_ATTR 
BOOLEAN 
NOT NULL
);     
--0 = Input, 1 = Output
CREATE INDEX
JOB_INSTANCE_CONTEXT_IDX 
ON
JOB_INSTANCE_CONTEXT(JOB_INSTANCE
_ID, 
ATTRIBUTE_KEY, IS_OUTPUT_ATTR);
CREATE TABLE
JOB_INSTANCE_COUNTERS (
JOB_INSTANCE_ID 
BIGINT NOT NULL,     
--reference to the job instance
18
COUNTER_NAME 
VARCHAR
(128) NOT NULL,  
--name of the counter set in tJobInstanceEnd for a counter
CO
UNTER_VALUE 
INTEGER,               
--value of the counter
CONSTRAINT
PK_JOB_INSTANCE_COUNTERS 
PRIMARY KEY
(JOB_INSTANCE_ID, COUNTER_NAME));
CREATE TABLE
JOB_INSTANCE_LOGS (
JOB_INSTANCE_ID 
BIGINT 
NOT NULL
,
LOG_TS 
TIMESTAMP 
NOT NULL
,
LOG_LEVEL 
VARCHAR
(10),
LOG_NAME 
VARCHAR
(128) 
NOT NULL
,
LOG_MESSAGE 
TEXT
);
CREATE INDEX
JOB_INSTANCE_LOGS_JOBID 
ON
JOB_INSTANCE_LOGS(JOB_INSTANCE_ID);

CREATE TABLE "PUBLIC"."UN_SL_ENTITY"
(
   DATAID integer,
   VERSIONNUM integer,
   FIRST_NAME varchar(255),
   UN_LIST_TYPE varchar(255),
   REFERENCE_NUMBER varchar(255),
   LISTED_ON varchar(255),
   COMMENTS1 varchar(2000),
   LIST_TYPE varchar(1000),
   LAST_DAY_UPDATED varchar(255),
   ENTITY_ALIAS varchar(1000),
   ENTITY_ADDRESS varchar(1000),
   SORT_KEY varchar(255),
   SORT_KEY_LAST_MOD varchar(255),
   NAME_ORIGINAL_SCRIPT varchar(1000),
   SUBMITTED_ON varchar(255),
   LOAD_DATE timestamp,
   LOAD_END_DATE timestamp,
   JOB_INSTANCE_ID bigint
)
;

CREATE TABLE "PUBLIC"."UN_SL_INDIVIDUAL"
(
   DATAID integer,
   VERSIONNUM integer,
   FIRST_NAME varchar(255),
   SECOND_NAME varchar(255),
   THIRD_NAME varchar(255),
   UN_LIST_TYPE varchar(255),
   REFERENCE_NUMBER varchar(255),
   LISTED_ON varchar(255),
   COMMENTS1 varchar(2000),
   DESIGNATION varchar(2000),
   NATIONALITY varchar(1000),
   LIST_TYPE varchar(1000),
   LAST_DAY_UPDATED varchar(255),
   INDIVIDUAL_ALIAS varchar(1000),
   INDIVIDUAL_ADDRESS varchar(1000),
   INDIVIDUAL_DATE_OF_BIRTH varchar(255),
   INDIVIDUAL_PLACE_OF_BIRTH varchar(1000),
   INDIVIDUAL_DOCUMENT varchar(2000),
   SORT_KEY varchar(255),
   SORT_KEY_LAST_MOD varchar(255),
   NAME_ORIGINAL_SCRIPT varchar(1000),
   FOURTH_NAME varchar(255),
   GENDER varchar(255),
   TITLE varchar(255),
   SUBMITTED_BY varchar(255),
   LOAD_DATE timestamp,
   LOAD_END_DATE timestamp,
   JOB_INSTANCE_ID bigint
)
;